# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CONTRIBUTING.md
      - MAINTAINERS.md
      - LICENSE
      - NOTICE
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_dispatch:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Compile the utilities & program
        shell: bash
        run: |
          CGO_ENABLED=0 go build -o integration-tester cmd/integration-tester/main.go
          
          CGO_ENABLED=0 go build -o load-generator cmd/load-generator/main.go
          
          CGO_ENABLED=0 go build -o process-exporter -a -tags netgo cmd/process-exporter/main.go

      - name: Run the integration test
        shell: bash
        run: |
          ./integration-tester -write-size-bytes 65536
